server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO

spring:
  # ???? ? ????? ???????? liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true # ???????????? SQL ????????? ??? ?????? ? ???????, ??????????? ORM
    # ??????????, ??? ORM ????? ?????? ? ??
    #hibernate:
      #ddl-auto: create # ??????? ? ??????? ?????
      #ddl-auto: validate # ????????, ??? ????????? ?? ????????????? ??????
