server:
  port: ${PORT:5000}

logging:
  level:
    root: INFO
    org:
      hibernate:
        type:
          descriptor.sql.BasicBinder: TRACE # логирование значений параметров запроса
          use_sql_comments: false # If enabled, the Hibernate generate comments inside the SQL. It is used to make debugging easier.

base-url: /api

spring:
  # путь к основному файлу миграции liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: true # It is used to display the executed SQL statements to console.
    # определяем, что ORM может делать с БД
    hibernate:
      ddl-auto: validate # проверка, что структура БД соответствует модели
      format_sql: true # чтобы sql был легко читаемым
